<a href="https://colab.research.google.com/github/saiswapnil123/AlertZone/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
res = np.random.randint(1,100)
print(res)

16


In [4]:
rng = np.random.default_rng()
res = rng.integers(1,100, size=(2, 5))
print(res)

[[31 73 82 26 94]
 [94 30 54 45 27]]


In [5]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
res = np.array([1,2,3], dtype='bool')
res2 = np.array([1,2,3], dtype='float')
res3 = np.array([1,2,3], dtype='complex')

print(res, res2, res3)

[ True  True  True] [1. 2. 3.] [1.+0.j 2.+0.j 3.+0.j]


In [13]:
temp = np.arange(1,10,2)
print(temp)
temp = np.arange(1,20,2, dtype='float').reshape(2,5)
print(temp)


[1 3 5 7 9]
[[ 1.  3.  5.  7.  9.]
 [11. 13. 15. 17. 19.]]


In [16]:
temp = np.ones((3, 4), dtype='int')
print(temp)
temp = np.zeros((3, 4), dtype='int')
print(temp)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [24]:
temp = np.random.random((3, 4))
print(temp, end="\n")
print("\n")
temp = np.random.randn(2, 3)
print(temp)


[[0.69455732 0.16522891 0.29878722 0.2617866 ]
 [0.18788538 0.73700032 0.94473052 0.85298612]
 [0.43876544 0.19202281 0.97223075 0.96807684]]


[[-0.75513033 -1.89715621  0.15872156]
 [-0.52916468  1.71162339 -0.72225465]]


In [26]:
test = np.linspace(-10, 10, 10)
print(test)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [28]:
test = np.identity(3)
print(test)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
a1 = np.arange(0, 10)
a2 = np.arange(0, 10).reshape(5, 2)
a3 = np.arange(0,10).reshape(1,2,5)


In [33]:
#ndim - what is the dimension of the array o the data
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [37]:
#shape - tells what is the shape of the data
print(a1.shape)
print(a2.shape)
print(a3.shape)
a3

(10,)
(5, 2)
(1, 2, 5)


array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [38]:
#size - total values in the data
print(a1.size)
print(a2.size)
print(a3.size)

10
10
10


In [41]:
#itemsize - tells what is the size of datatype used (float - 8 bytes)
print(a1.itemsize)
#dtype - tells waht data type is the data


8


In [45]:
#astype - change the data type
a1.astype('float')
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [47]:
 ## Arthimetic Operations ##

In [48]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [50]:
##Scalar Operation ##

#arthimetic ( +, -, /, **, %)
a1 % 2


array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [53]:
## Relational Operation ## ( >, <, !=, ==, >=, <= )
a2 != 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [54]:
## Vector Operations ## ( Same as scalar operations but between vectors)

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [56]:
## Array Functions ##

a1 = np.random.random((3, 5))
a2 = np.round(a1 * 100)
print(a1, '\n', a2)

[[0.68614485 0.16427179 0.83457843 0.61499753 0.17307998]
 [0.15386516 0.41705865 0.39545504 0.80847664 0.04831766]
 [0.7337829  0.67077952 0.2653561  0.73208567 0.0234884 ]] 
 [[69. 16. 83. 61. 17.]
 [15. 42. 40. 81.  5.]
 [73. 67. 27. 73.  2.]]


In [62]:
np.sum(a1)
np.prod(a2)
np.min(a1)
np.max(a2)
np.min(a1, axis= 1) # axis = 1 for rows and 0 for col
np.mean(a1)
np.median(a2)
np.std(a1)
np.var(a2)
a1 = a1.reshape(5, 3)
np.dot(a1, a2)
np.exp(a1)
np.log(a2)

array([[110.73229703,  73.7944876 ,  86.05451181, 116.08507622,
         14.15497827],
       [ 56.26318626,  27.41828551,  62.12235389,  62.76648477,
         11.6280883 ],
       [ 93.72766761,  77.44998509,  72.26293901, 116.49123072,
         10.68422557],
       [ 63.3075674 ,  76.53419242,  51.47272901, 111.35069738,
          5.83187379],
       [ 31.00550901,  36.5670183 ,  51.94216987,  77.2003143 ,
          8.21845886]])